### PR TITLE
(#10347) Add hiera_class Puppet function

### PR DESCRIPTION
**Pull request by seanmil**
hiera_class provides the ability to include parameterized classes
in Puppet via a Hiera search.

### CODE REVIEW

**Comment by hunner** [comment]
That's awesome! +1

**Comment by dkerwin** [comment]
Great! +1

**Comment by kelseyhightower** [comment]
@seanmil Sorry we are getting around to this so late, but could you rebase this on master? Once that is done I can give this a review.

**Comment by kelseyhightower** [comment]
@seanmil I'm closing this pull request, not because I think this is a bad feature, but I think we should release this in a separate repo so users can start playing with this immediately. Based on feedback from the community we can reconsider this for inclusion in hiera-puppet.

**Pull request closed without merging**
